[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "pythagoras"
version = "0.1.0"
description = "Shiny-for-Python app with card-based analytics"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Nick Ward" }]
dependencies = [
  "faicons>=0.2",
  "geopandas>=1.0",
  "jsonschema>=4.0",
  "numpy>=1.24",
  "pandas>=2.0",
  "plotly>=5.18",
  "pyarrow>=14",
  "requests>=2.0",
  "session-info>=1.0",
  "shapely>=2.0",
  "shiny>=1.0",
  "shinywidgets>=0.3.1",
  "xarray",
  "scipy>=1.10",
  "mlxtend>=0.23",
  "scikit-learn>=1.4",
  "shinylive==0.8.11",
  "cards>=2.0.0",
  "card>=0.0.1",
  "roles>=1.0.0",
]

[tool.hatch.build]
include = [
  "app/**",
]
