---
format:
  html:
    css: markdown.css
    page-layout: full
    embed-resources: true
    minimal: true
editor:
  render-on-save: true
backgroundcolor: "#d2e5f4"
---

# 🧩 Missing Values
The assessment and resolution of missing values is multifaceted.

Firstly, the true missing values must be identified. This involves [identifying placeholders](#placeholders) for missing values. For example, addresses that hold the value "unknown". Conversely, it also involves assigning obvious values to certain missing values through domain knowledge and careful reasoning. 

After this each predictor in a dataset needs to have its missing values assessed with respect to [prevalence](#prevalence), [cause](#cause), [association](#association], and the [nature](#nature) of any missing values. It is important to determine these as they drive how missingness in each predictor should be handled. These are explained in the section called [Assessment](#assessment).

Finally, the resolution of missing values encompasses the use of [shadow variables](#shadow), [variable removal](#variable), [observation removal](#observation), imputation and [implicit missing value tolerance](#implicit).
Imputation can be [manual](#manual) or [learned](#learned). A mixture of several methods may be optimal. These are explained in the section called [Resolution](#resolution).

# 📋 Assessment

When assessing missingness it is useful to ask the following question of the data:

> _Is the missingness due an artifact of data curation or intrinsic to the ongoing data-generating and data-collection processes?_

In other words, will the missingness continue into the foreseeable future or will it cease because it was due to merely historic problems. 
__If any missingness can be expected into the future, ensure the model can tolerate this in its "prediction" mode.__

## 📊 Prevelence

The prevelence levels are:

- **Excessively missing** - A predictor whose missing values exceed an acceptability threshold 
- **Somewhat missing** - A predictor whose missing values fall below an acceptability threshold 
- **Not missing** - A predictor without missing values

It is best to assess predictor prevelence _after_ excessively missing observations are removed.
Excessively missing variables are best removed _except_ it can be shown that they are important predictive variables.

## 🔍 Cause

The possible causes of missingness are:

-   **Random** - A predictor's missingness has no pattern with respect to the non-missing values of other predictors. This cause is also known as *Missing-completely-at-random (MCAR)*
-   **Patterned** - A predictor's missingness has a statistically significant model that predicts much of the missing values using the (non-missing) values of other predictors. This cause is also known as *Missing-at-random (MAR)*
-   **Explainable** - A predictor's missingness can be explained by the values that would have existed. By its nature, this is difficult to diagnose using the data. This cause is also known as *Missing-not-at-random (MNAR)* 

## 🔗 Association

Variables often have similar causes of missingness that show as correlated missingness. The sharing of _common_ causes or _shared_ causes between predictors can be assessed through the use of __Association rules__, __Jaccard Index__, and the __Upset Chart__. 

When association is present, this can lead to observations having either few or many missing values. The distribution of observation missingness may show a bimodal

## 🧬 Nature

In addition there is a nature of missingness to consider:

-   **Informative**  - A predictor's missingness may be predictive of the target.
-   **Uninformative**  - A predictor's missingness may not be predictive of the target.


# ✅ Resolution

The resolution of missing values is about ending up with a dataset that no longer has missing values. Doing so needs to procede in a particular order.

## 📍 1 Placeholders for missing-values {#placeholders}
Not all non-missing values are real. Sometimes, when a entry is compulsory, people will enter a placeholder value to indicate that they have no valid value to offer. For numeric values, -99 has historically suggested that the value is effectively missing. An address that is written as "unknown" again signifies missing data. All such candidate values need to be judged as to whether they are converted to missing values.

Issues:

 -  It requires domain knowledge to reliably assign placeholders to missing values.

>Example:  
>_When a patient is given the name "Jane Doe", the suggestion is that the name is not actually known. Combining the records of all the "Jane Does" would be a bad idea._

## ✍️ 2 Manual imputation {#manual}
_Manual imputation_ is the process of in-filling certain __explainable__ missing values based upon logic and domain knowledge. This need not apply to all the missing values of a single variable. Sparse data is a classic example of the need to manualy assign values to the missing values.

> _Sparse data is a dataset where most values are zero, empty, or missing. This happens when a large table has very few actual entries compared to its total size. Common examples include:_  

>> * _Movie ratings: Most users rate only a few films out of thousands available._
>> * _Word lists: Most documents use only a tiny fraction of all words in a dictionary._
>> * _Online shopping: Most buyers purchase only a few items from a huge store._


Issues:

 - _Manual imputation_ needs to occur before any other resolution so that only __unexplainable__ missing values get down-stream processing.
 - Ideally this is done programmatically and is carefully documented for repeatability.
 - Consider whether the programmed in-filling is able to be applied when predicting future observations (in production) which might also contain missing values.

>Example:  
>_Blood-test results can be missing because no diagnostic justification for the test has yet arisen. Were such tests undertaken unnecessarily they would usually yield results in the normal range (rather than in the extreme range). A possible manual imputation might involve substituting a typically "Normal" result for each missing test. Substituting a mean result (as __learned imputation__ might) would be a __poor__ choice._


## 🌘 3 Shadow variables {#shadow}
Shadow variables are additional binary variables manufactured to record which values are missing.  When the missing values have an **Informative** nature, a shadow variable supplies this valuable information to the model-fitting even if the values are subsequently imputed. 

Issues:

- _Shadow variable_ production needs to occur before any imputation.
- When the missing values are **Uninformative** the additional _shadow variables_ will be no use. A variable selection stage should attempt to remove unnecessary _shadow variables_.

>Example:  
>_The absence of clinical notes is often caused by periods of high workload and surgery emergencies. The target may also be affected by periods of high workload and surgery emergencies. This absence of clinical notes may be informative and a shadow variable should be generated to capture this information._

## ✂️ 4 Variable removal {#variable}
Whan a variable has a large percentage of missing values, a threshold may be reached where it becomes challenging to perform _learned imputation_, and the alternative data loss due _Observation removal_ becomes excessive. 

Issues:

 - That threshold point changes depending upon the "importance" of the variable to the target. Best practice would be to vary this as a hyperparameter during model tuning.
 - _Variable removal_ must preceed _Observation removal_ to maximise the number of training observations when these resolutions are used in conjunction.

>Example:  
>_Polio protocols have remained absent for decades. The data is more missing than present. This variable deserves to be removed until further notice._

## 🗑️ 5 Observation removal {#observation}
_Observation removal_ involves the deletion of observations with (relevant) missing values. This leaves a reduced number of entirely complete observations with which to fit the model.
This resolution style is also known as _Partial deletion_. A more sophisticated variation of this idea can be employed to only remove observations whose incompleteness exceeds a certain threshold.

Issues:

 - What constitutes excessive missingness is poorly defined. Best practice would be to vary this threshold as a hyperparameter during model tuning.
 - _Observation removal_ risks introducing data bias if there is some pattern to the missing values. Only truely random missingness is guartanteed to avoid data bias. 
 - What constitutes relevant predictors may not yet be clear. If a model ends up using only 10 out of 40 predictors, then these 10 are the relevant ones. Best practice would be to iterate through a range of variable importances to discover what might be relevant to _Observation removal_.
 - The number of observations decreases leading to weaker model fitting. This makes _Observation removal_ something to increasingly avoid with smaller sample sizes. 

>Example:  
>_Instrument failures prevent the recording of routine blood pressure readings. Records involving missed BP readings can be safely ignored as they are believed to occur randomly. No data bias can be associated with a random process._

## 🧠 6 Learned imputation {#learned}
_Learned imputation_ is a process of predicting the missing values. It enables observations to remain in the training sample dispite being incomplete. This is also known as _Statistical imputation_.

Issues:

 - It is wrong to think that _Learned imputation_ will necessarily provide accurate predictions. This can be explored by generating CV metrics for such models.
 - If the observations are truly independent and predictors are truely independent, then _Learned imputation_ will necessarily be on a par with a constant value estimation.
 - Some complex imputation techniques are slow to train.
 - Learned imputation has a role to play even in the absence of missing values. The reason for generating a missing value predictor may lie with future in complete observations (in production)
 - Learned imputation need good predictors. Feature extraction may need to be performed **before** a strong imputation model can be built.

>Example:  
>_The absence of clinical notes is often caused by periods of high workload and surgery emergencies. This is not random: it happens frequently on Friday and Saturday nights. The missing notes might best be estimated by a note typical of the day-of-week and time. Day-of-week needs to be extracted from the observation date first in order to facilitate the imputation training._

## 👻 7 Implicit missing value tolerance {#implicit}
Many models are capable of tolerating missing values by applying a strategy that either removes observations or implcitly imputes according to their proprietory algorithm. 
Many "Tree" models employ a form of _Learned imputation_. Many "Linear" models employ a form of _Observation removal_. 

Issues:

 - If you are trialing many model types, some of which have no _Implicit missing value tolerance_ (e.g. SVM), you will need to explicitly employ _Learned imputation_ (or _Observation removal_) for all models, in order to provide a fair trial of all models. 
 - Whether a particular model type has _Implicit missing value tolerance_ is often unclear. Intolerant ones may or may not prove exceptions that explain the intolerance clearly.
 - Though more convenient, _Implicit missing value tolerance_ should be be assumed to lead to a better result than explcit management of missing values.

>Example:  
>_XGBoost is a good general modelling method that copes well with missing data. Since it is the sole method being considered in the study, I can bypass some missing-value issues. I still need to consider a) missing-value placeholders, b) Manual imputation of explainable missing-values, c) excessive variable missingness, d) excessive observation missingness, and e) Shadow variables for informative missingness._
