---
format:
  html:
    embed-resources: true
    minimal: true
editor:
  render-on-save: true
---
#### 🧭 Introduction


Each predictor in a dataset needs to have its missing values assessed with respect to __prevalence__, __cause__ and the __nature__ of any missing values.
It is important to determine __prevalence__, __cause__ and the __nature__ as they drive how missingness in each predictor should be handled.

##### Prevelence

The prevelence levels are:

- **Excessively missing** - A predictor whose missing values exceed an acceptability threshold 
- **Somewhat missing** - A predictor whose missing values fall below an acceptability threshold 
- **Not missing** - A predictor without missing values

It is best to assess predictor prevelence _after_ excessively missing observations are removed.
Excessively missing variables are best removed _except_ it can be shown that they are important predictive variables.

##### Cause

The possible causes of missingness are:

-   **Random** - A predictor's missingness has no pattern with respect to the non-missing values of other predictors. This cause is also known as *Missing-completely-at-random (MCAR)*
-   **Patterned** - A predictor's missingness has a statistically significant model that predicts much of the missing values using the (non-missing) values of other predictors. This cause is also known as *Missing-at-random (MAR)*
-   **Explainable** - A predictor's missingness can be explained by the values that would have existed. By its nature, this is difficult to diagnose using the data. This cause is also known as *Missing-not-at-random (MNAR)*

The sharing of _common_ causes or _shared_ causes between predictors can be assessed through the use of Association rules, Jaccard Index, and the Upset chart.

##### Nature

In addition there is a nature of missingness to consider:

-   **Informative**  - A predictor's missingness may be predictive of the target.
-   **Uninformative**  - A predictor's missingness may not be predictive of the target.

#### This card

This card focuses on differentiating between **Informative** and **Uninformative** natures of missingness. The following possible assesments are calculated based upon a decision tree trying to predict the target with and without shadow variables:

#### 🔄 Flip side

The back of the card documents a table of predictors with missing values. Each row gives an assessment and the basis of that decision. The rows can be sorted into descending p-value clicking the p-value header. 


#### ⚙️ Settings

Use the Tour Guide button to learn about the settings of this card.

#### Goal

1. _Primary:_ To identify predictors that have patterned missingness. Their missing values should be imputed rather than removing the observations (partial deletion). Deleting observations with patterned missingness will produce non-random omissions that are likely to cause data bias. 
1. _Secondary:_ To detect relationships that suggest an explanation and possibly a manual imputation for certain missing values. For example, in a housing dataset, the category level of "house boat" might explain why the rateable-value variable is missing (manually set these to zero).

***
All cards downstream of this card will receive any changes enacted by this card.


&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
The goal of this card is to assign to each variables that has missing values what the type of missingness is. 

There is a secondary goal of creating shadow variables to allow for informative missingness.

##### Shadow variables

It is possible to add extra binary predictors that supply information about whether a value is/was missing. This is a form a feature extraction. 
Once imputed, a missing value would be indistinguishable from a non-missing value unless a shadow variable keeps this information available. 
Since only the predictor role can normally have missing values, only predictor variables will be considered for shadow variables.

##### Informative missingness

The presence of missing values can potentially assist in predicting the target. When this occurs we have "informative missingness". It is important to create shadow variables so that this relationship can be exploited during modeling. Feature selection can later exclude the shadow variables if they prove uninformative.


##### Random Type

Values that are randomly missing are reliably unbiased by virtue of being randomised.

This type of missingness means any attempts at partial deletion, or imputation, have a strong case for being *unbiased*. This means the any statistics from the data should not be biased due to the missing values. However the statistics confidence interval may be widened as a result.

##### Patterned Type

Values whose missingness is patterned can be said to have a probability of missingness that can be predicted to an extent that is statistically better than guessing. This is a set of classification problems. The target is each variable's binary missingness; the predictors are the other variable values. One can also add the sequence number of observations, in case missingness is a time-dependent process.

This type of missingness means any attempts at partial deletion have a strong case for being *biased*. This means that statistics from the data might be biased if partial deletion is employed. The use of imputation does not present a strong case for bias. Imputation is the preferred solution to patterned missingness.

##### Because Type

Values that are missing because of the unseen values. For example,

> Blood-test results can be missing because no diagnostic justification for the test has yet arisen. Were such tests undertaken unnecessarily they would usually yield results in the normal range. A possible manual imputation would involve substituting a typically "Normal" result for each missing test. Substituting a mean result would be a poor choice.

We cannot detect the last type of missingness since the information needed is withheld from us due to being missing. This must be manually analysed through a reasoning process involving what might motivate values to be withheld in the data collection process.

This type of missingness means that statistics from the data might be *biased*, since this type of missingness is a form of sampling bias. This is the worst type of missingness and also the most difficult to detect. Sometimes a reasonable manual imputation strategy exists for this type of missingnes.

#### Actions

Once each variable's type of missingness are distinguished between *Random*, *Patterned* and *Because* the following actions might be possible:

-   Design manual-imputation strategies for some variables (esp. *Because* types)

-   Design statistical-imputation strategies for *Random* and *Patterned* type variables.

-   Design partial-deletion strategies for *Random* type variables.

-   Create shadow variables **before** any imputation 
